# Generated by Django 2.0.1 on 2018-03-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180312_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
