# Generated by Django 2.0.1 on 2018-03-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20180325_1543'),
        ('inventory', '0003_auto_20180312_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='awarded_badges',
            field=models.ManyToManyField(blank=True, related_name='equipment_with_badge_awarded', to='userprofile.Badge'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='prerequisite_badges',
            field=models.ManyToManyField(blank=True, related_name='equipment_with_badge_prerequisite', to='userprofile.Badge'),
        ),
    ]
