# Generated by Django 2.0.1 on 2018-03-31 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180331_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='awarded_badges',
        ),
    ]
