# Generated by Django 2.0.1 on 2018-04-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_equipment_awarded_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentcheckout',
            name='checkout_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='equipmentcheckout',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
