# Generated by Django 2.0.1 on 2018-06-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_equipment_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentcheckout',
            name='checkout_status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('CHECKED_OUT', 'Checked Out'), ('RETURNED', 'Returned'), ('CANCELED', 'Canceled')], default='RESERVED', max_length=15),
        ),
    ]
