# Generated by Django 2.0.1 on 2018-06-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20180605_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='checkout_timeframe',
            field=models.CharField(choices=[('CHECKOUT_3HR', '3hr checkout'), ('CHECKOUT_24HR', '24hr checkout'), ('CHECKOUT_WEEK', 'Thurs-Tues checkout')], default='CHECKOUT_WEEK', max_length=15),
        ),
    ]
