# Generated by Django 2.0.1 on 2019-05-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20180608_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=15)),
                ('begin_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'closed day',
                'verbose_name_plural': 'closed days',
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='checkout_timeframe',
            field=models.CharField(choices=[('CHECKOUT_3HR', '3hr checkout'), ('CHECKOUT_24HR', '24hr checkout'), ('CHECKOUT_WEEK', 'Checkout due Tues')], default='CHECKOUT_WEEK', max_length=15),
        ),
    ]
