# Generated by Django 2.0.1 on 2018-02-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=255, null=True)),
                ('course_description', models.CharField(max_length=255, null=True)),
                ('course_duration', models.CharField(max_length=255, null=True)),
                ('course_capacity', models.IntegerField(null=True)),
            ],
        ),
    ]
