# Generated by Django 2.0.1 on 2018-02-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
