# Generated by Django 2.0.1 on 2018-03-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_prerequisitecourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prerequisitecourses',
            name='course_id',
        ),
        migrations.DeleteModel(
            name='PrerequisiteCourses',
        ),
    ]
