# Generated by Django 2.0.1 on 2018-03-06 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_badge'),
        ('courses', '0005_auto_20180306_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_avaliable', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_capacity',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_duration',
        ),
        migrations.AddField(
            model_name='course',
            name='awarded_badges',
            field=models.ManyToManyField(related_name='awarded', to='userprofile.Badge'),
        ),
        migrations.AddField(
            model_name='course',
            name='prereq_badges',
            field=models.ManyToManyField(related_name='prerequisites', to='userprofile.Badge'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
