# Generated by Django 2.0.1 on 2018-03-06 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_auto_20180306_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegisteration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.TextField(default='0')),
            ],
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='seat_avaliable',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
        migrations.AddField(
            model_name='courseregisteration',
            name='course_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseSection'),
        ),
        migrations.AddField(
            model_name='courseregisteration',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
