# Generated by Django 2.0.1 on 2018-03-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180306_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prereq_badges',
            field=models.ManyToManyField(null=True, related_name='prerequisites', to='userprofile.Badge'),
        ),
    ]
