# Generated by Django 2.0.1 on 2018-02-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentcheckout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('make', models.CharField(max_length=255, null=True)),
                ('model', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sub_category', models.CharField(choices=[('MICROPHONE', 'Microphone'), ('WIRELESS', 'Wireless'), ('CASE', 'Case'), ('STAND', 'Stand'), ('CABLE', 'Cable'), ('HEADPHONES', 'Headphones'), ('TELEPROMPTER', 'Teleprompter'), ('GREEN_SCREEN', 'Green screen'), ('CAMERA', 'Camera'), ('LIGHT_KIT', 'Light kit')], default='MICROPHONE', max_length=15)),
                ('category', models.CharField(choices=[('CHECKOUT_24HR', '24hr checkout'), ('CHECKOUT_WEEK', 'Thurs-Tues checkout')], default='CHECKOUT_WEEK', max_length=15)),
            ],
        ),
    ]
