# Generated by Django 2.0.1 on 2018-02-13 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20180210_2117'),
        ('equipmentcheckout', '0002_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentcheckout',
            name='equipmentID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipmentcheckout.Equipment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentcheckout',
            name='projectID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
            preserve_default=False,
        ),
    ]
