# Generated by Django 2.0.1 on 2018-02-15 22:19

from django.db import migrations, models
import equipmentcheckout.models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentcheckout', '0003_auto_20180213_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.FileField(null=True, upload_to=equipmentcheckout.models.handle_file_upload),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manual_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
