# Generated by Django 2.0.1 on 2018-02-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentcheckout', '0004_auto_20180215_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='checkout_timeframe',
            field=models.CharField(choices=[('CHECKOUT_24HR', '24hr checkout'), ('CHECKOUT_WEEK', 'Thurs-Tues checkout')], default='CHECKOUT_WEEK', max_length=15),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('LIGHTING', 'Lighting')], default='AUDIO', max_length=15),
        ),
    ]
