# Generated by Django 2.0.1 on 2018-02-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentcheckout', '0006_equipment_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
