# Generated by Django 2.0.1 on 2018-02-24 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentcheckout', '0007_equipmentcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipmentcheckout.EquipmentCategory'),
        ),
    ]
