# Generated by Django 2.0.1 on 2018-02-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentcheckout', '0011_equipment_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='category',
            new_name='equipment_category',
        ),
    ]
