# Generated by Django 2.0.1 on 2018-02-24 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentcheckout', '0012_auto_20180224_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_category',
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipmentcheckout.EquipmentCategory'),
            preserve_default=False,
        ),
    ]
