# Generated by Django 2.0.1 on 2018-02-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentcheckout', '0013_auto_20180224_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='category',
        ),
    ]
