# Generated by Django 2.0.1 on 2018-02-24 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentcheckout', '0015_equipment_equipment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_category',
        ),
        migrations.AddField(
            model_name='equipment',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipmentcheckout.EquipmentCategory'),
            preserve_default=False,
        ),
    ]
