# Generated by Django 2.0.1 on 2018-02-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentcheckout', '0016_auto_20180224_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='cat',
        ),
    ]
