# Generated by Django 2.0.1 on 2018-02-24 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentcheckout', '0017_remove_equipment_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='this_isnt_a_fucking_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipmentcheckout.EquipmentCategory'),
            preserve_default=False,
        ),
    ]
