# Generated by Django 2.0.1 on 2018-02-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentcheckout', '0018_equipment_this_isnt_a_fucking_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='this_isnt_a_fucking_field',
        ),
    ]
