# Generated by Django 2.0.1 on 2018-02-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentcheckout', '0020_equipment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
