# Generated by Django 2.0.1 on 2018-02-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentcheckout', '0021_auto_20180224_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
