# Generated by Django 2.0.1 on 2018-02-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentcheckout', '0022_auto_20180224_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
