# Generated by Django 2.0.1 on 2018-02-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentcheckout', '0025_auto_20180225_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'equipment', 'verbose_name_plural': 'inventory'},
        ),
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='equipmentcheckout',
            options={'verbose_name': 'checkout', 'verbose_name_plural': 'checkouts'},
        ),
    ]
