version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 8000:8000
    volumes:
      - ./src/static:/var/www/static
      - ./nginx/sites-enabled.conf:/etc/nginx/conf.d/sites-enabled.conf
    depends_on:
      - django

  django:
    build: ./src
    command: ./wait-for-it.sh postgres:5432 -- python /usr/src/app/manage.py runserver 0:8080
    volumes:
      - ./src:/usr/src/app
      - ./src/static/media:/media
    depends_on:
      - postgres
    links:
      - redis
    env_file:
      - .env

  celery:
    build: ./src
    # command: celery multi start w1 -A faypublic -l info && celery -A faypublic beat -l info
    command: ./wait-for-it.sh postgres:5432 -- celery -A faypublic worker -l info -B
    volumes:
      - ./src:/usr/src/app
    links:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis