version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 8000:8000
    volumes:
      - ./src/static:/var/www/static
      - ./nginx/sites-enabled.conf:/etc/nginx/conf.d/sites-enabled.conf
    depends_on:
      - django

  django:
    build: ./src
    command: python /usr/src/app/manage.py runserver 0:8080
    volumes:
      - ./src:/usr/src/app
      - ./src/static/media:/media
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres
    env_file:
      - .env