version: '3'

services:
  nginx:
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src/static:/var/www/static
      - ./nginx/sites-enabled.prod.conf:/etc/nginx/conf.d/sites-enabled.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  django:
    restart: always
    command: gunicorn -w 3 --bind 0.0.0.0:8080 faypublic.wsgi

  postgres:
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data

  celery:
    restart: always

  redis:
    restart: always

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot