# Generated by Django 2.0.1 on 2018-02-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectupload',
            name='uploaded_file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
