# Generated by Django 2.0.1 on 2018-02-07 16:19

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('project', '0002_auto_20180207_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to='userprofile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='projectupload',
            name='uploaded_file',
            field=models.FileField(upload_to=project.models.handle_file_upload),
        ),
    ]
