# Generated by Django 2.0.1 on 2018-02-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
