# Generated by Django 2.0.1 on 2018-02-10 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20180210_2025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectUpload',
            new_name='ProjectSubmission',
        ),
    ]
