# Generated by Django 2.0.1 on 2018-02-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20180210_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='admin_submission_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='scheduled_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='user_submission_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SCHEDULED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=15),
        ),
    ]
