# Generated by Django 2.0.1 on 2018-02-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20180210_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsubmission',
            old_name='admin_submission_notes',
            new_name='admin_notes',
        ),
        migrations.RenameField(
            model_name='projectsubmission',
            old_name='user_submission_notes',
            new_name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
