# Generated by Django 2.0.1 on 2018-02-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20180210_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='expected_completion_date',
            field=models.DateField(null=True),
        ),
    ]
