# Generated by Django 2.0.1 on 2018-03-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_project_expected_completion_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='projectsubmission',
            options={'verbose_name': 'submission', 'verbose_name_plural': 'submission'},
        ),
    ]
