# Generated by Django 2.0.1 on 2018-04-18 15:08

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20180418_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsubmission',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=project.models.handle_file_upload),
        ),
        migrations.DeleteModel(
            name='ProjectSubmission',
        ),
    ]
