# Generated by Django 2.0.1 on 2018-04-18 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_programrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='programrequest',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SCHEDULED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='programrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
