# Generated by Django 2.0.1 on 2018-05-17 20:19

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20180418_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programrequest',
            name='media_link',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=project.models.handle_file_upload, validators=[project.models.validate_video_extension]),
        ),
    ]
