# Generated by Django 2.0.1 on 2018-07-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20180517_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='programrequest',
            name='contains_mature_content',
            field=models.BooleanField(default=False),
        ),
    ]
