# Generated by Django 3.0.5 on 2022-02-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_programrequest_contains_mature_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='media_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
