# Generated by Django 2.0.1 on 2018-04-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_userprofile_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
