# Generated by Django 2.0.1 on 2018-04-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_badge_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='get_email_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='get_sms_reminders',
            field=models.BooleanField(default=False),
        ),
    ]
