# Generated by Django 2.0.1 on 2018-04-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20180409_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='get_email_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='get_sms_reminders',
            field=models.BooleanField(default=False),
        ),
    ]
