# Generated by Django 2.0.1 on 2018-04-18 23:19

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20180409_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.FileField(null=True, upload_to=userprofile.models.handle_file_upload, validators=[userprofile.models.validate_photo_extension]),
        ),
    ]
