# Generated by Django 2.0.1 on 2018-07-08 21:44

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='how_did_you_hear_about_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to=userprofile.models.handle_file_upload, validators=[userprofile.models.validate_photo_extension]),
        ),
    ]
