# Generated by Django 2.0.1 on 2018-07-08 22:35

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20180708_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='proof_of_residency',
            field=models.FileField(blank=True, null=True, upload_to=userprofile.models.handle_proof_of_residency_upload),
        ),
    ]
