# Generated by Django 3.0.5 on 2020-04-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_auto_20180722_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='get_email_reminders',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='get_sms_reminders',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
