# Generated by Django 2.0.1 on 2018-03-08 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0002_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_title', models.CharField(max_length=255, null=True)),
                ('class_description', models.TextField(null=True)),
                ('awarded_badges', models.ManyToManyField(related_name='awarded', to='userprofile.Badge')),
                ('prereq_badges', models.ManyToManyField(blank=True, related_name='prerequisites', to='userprofile.Badge')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.TextField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_avaliable', models.IntegerField(blank=True, default=6, null=True)),
                ('class_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Class')),
            ],
        ),
        migrations.AddField(
            model_name='classregistration',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.ClassSection'),
        ),
        migrations.AddField(
            model_name='classregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
