# Generated by Django 2.0.1 on 2018-03-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_badge'),
        ('classes', '0002_auto_20180308_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'class', 'verbose_name_plural': 'classes'},
        ),
        migrations.AlterModelOptions(
            name='classregistration',
            options={'verbose_name': 'registration', 'verbose_name_plural': 'registrations'},
        ),
        migrations.AlterModelOptions(
            name='classsection',
            options={'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.RemoveField(
            model_name='class',
            name='prereq_badges',
        ),
        migrations.RemoveField(
            model_name='classregistration',
            name='score',
        ),
        migrations.AddField(
            model_name='class',
            name='prerequisite_badges',
            field=models.ManyToManyField(blank=True, null=True, related_name='prerequisites', to='userprofile.Badge'),
        ),
        migrations.AddField(
            model_name='classregistration',
            name='score_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='seat_avaliable',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
