# Generated by Django 2.0.1 on 2018-03-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20180310_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='awarded_badges',
            field=models.ManyToManyField(blank=True, related_name='awarded', to='userprofile.Badge'),
        ),
        migrations.AlterField(
            model_name='class',
            name='prerequisite_badges',
            field=models.ManyToManyField(blank=True, related_name='prerequisites', to='userprofile.Badge'),
        ),
    ]
