# Generated by Django 2.0.1 on 2018-03-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_class_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
