# Generated by Django 2.0.1 on 2018-03-24 15:18

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20180312_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classsection',
            old_name='class_key',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='classsection',
            old_name='seat_avaliable',
            new_name='seats',
        ),
        migrations.AddField(
            model_name='classsection',
            name='date',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
    ]
