# Generated by Django 2.0.1 on 2018-03-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20180324_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classsection',
            old_name='course',
            new_name='class_key',
        ),
        migrations.RenameField(
            model_name='classsection',
            old_name='seats',
            new_name='seat_avaliable',
        ),
        migrations.RenameField(
            model_name='classsection',
            old_name='date',
            new_name='start_date',
        ),
    ]
