# Generated by Django 2.0.1 on 2018-03-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_auto_20180324_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classsection',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='classsection',
            old_name='seat_avaliable',
            new_name='seats_avaliable',
        ),
    ]
