# Generated by Django 2.0.1 on 2018-04-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_auto_20180331_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classsection',
            old_name='seats_avaliable',
            new_name='seats_available',
        ),
    ]
